### ISSUE TITLE
Connection loss leads to breakage of the plugin

### ISSUE THREAD

**Issue by Folas1337** [Phoenix616/ConnectorPlugin#12]
### What is happening?

If wherever the plugin is running loses connection to the redis server, it'll leave the plugin in a state where it's unusable.

### What did you expect to happen?

I would like the plugin to attempt reconnecting if the connection ever breaks so it can recover into a healthy state after the lost connection is re-established.

### Version

build 90 of ConnectorPlugin

### Config

```YAML
# Plugin debugging
debug: true

# Currently supported types:
# - "plugin_messages" (will not be able to send messages from server without any players online)
# - "redis" (does not require online players)
# - "mqtt" (does not require online players)
messenger-type: redis

# The group this server is in
group: global

# Put specific plugins into different groupings
plugin-groups:
  pluginname: specialgroup

# Should be the same name as in the proxy config
server-name: ... redacted ...

# Redis messenger settings
redis:
  host: ... redacted ...
  port: 6379
  db: 0
  timeout: 60
  password: ... redacted ...

# Mqtt messenger settings
mqtt:
  broker-uri: tcp://localhost:1883
  keep-alive: 30
  username: mqttuser
  password: password1
```

### Server/system Version

Paper version 1.21.3-65-master@7e789e8

### Log

```shell
There are a couple lines reading like this:
[06:12:57] [lettuce-nioEventLoop-4-3/WARN] [de.themoep.connectorplugin.lib.lettuce.core.protocol.ConnectionWatchdog]: Cannot reconnect to [... redacted .../<unresolved>:6379]: ... redacted ...
```

### What other programs/plugins are you running?

Lots but they should have very little to do with this bug/request
