### ISSUE TITLE
Unable to Utilize VelocityConnectorPlugin

### ISSUE THREAD

**Issue by Kas-tle** [Phoenix616/ConnectorPlugin#3]
#### Used Version
```
 [06:26:37 INFO]: Loaded plugin connectorplugin 1.3-SNAPSHOT (build 54) by Phoenix616
```
 
#### Config

 ```yaml
# Plugin debugging
debug: true

# A unique ID for this proxy
server-id: "velocity-01"

# Currently supported types:
# - "plugin_messages" (will not be able to send messages to servers without any players online, messages will be queued)
# - "redis" (does not require any online players)
# - "mqtt" (does not require any online players)
messenger-type: redis

# Redis messenger settings
redis:
  host: 172.18.0.1
  port: 6380
  db: 0
  timeout: 60
  password: ***
 ```
 
#### Environment description
```
[09:12:10 INFO]: Velocity 3.1.2-SNAPSHOT (git-74edac96-b153)
```
 
 
#### Full Log
No output is produced.

#### What other programs/plugins are you running?
I am attempting to use my [core plugin](https://github.com/Paradisu/ParadisuPlugin/tree/master/velocity/src/main/java/net/paradisu/paradisuplugin/velocity) on Velocity to obtain the position of a player.

#### What is happening?
I register the VelocityConnectorPlugin here:
https://github.com/Paradisu/ParadisuPlugin/blob/master/velocity/src/main/java/net/paradisu/paradisuplugin/velocity/Paradisu.java#L69-L78
My plugin does seem to see it as `connectorEnabled` is logged as true on startup.

The command I am attempting to use (through the cloud framework) is registered here:
https://github.com/Paradisu/ParadisuPlugin/blob/master/velocity/src/main/java/net/paradisu/paradisuplugin/velocity/commands/command/LocateCommand.java#L34-L61

On running `/locateplayer player`, the only output produced is a logging of the connector instance and a message to the sender that the command was executed. Nothing in the `whenComplete` seens to occur, so I think that the completable future is just never returning. I could not find any examples of registering the plugin on Velocity, so I tried as best I could. It is very possible I messed up.

I has also tried bringing in LocationInfo and manually completing a completable future with some dummy location info. Passing that into `whenComplete` successfully returns the location info.

Also, I should add that the actions themselves that are called from the bridge do, in fact, occur. For example, calling teleport here:
https://github.com/Paradisu/ParadisuPlugin/blob/master/velocity/src/main/java/net/paradisu/paradisuplugin/velocity/commands/command/TeleportCommand.java#L33-L52

However, if I attempt to place the `sendMessage` in the `whenComplete`, neither the success nor the failure condition is ever executed. So it would seem that something specific to velocity is going on here with the completable futures, and whatever it is seems to be shared by, at minimum, all of the bridge methods.

#### What did you expect to happen?
The location info should be returned by the completable future. 

#### Additional context
Also discussed over Discord with phoenix616. Posting here as well for completeness and to consolidate all the information.

The ConnectorPlugin inbuilt commands work flawlessly, so I do not believe there is an issue with the messaging between the servers.
