### ISSUE TITLE
Cross server transfer failed

### ISSUE THREAD

**Issue by lipind** [Phoenix616/ConnectorPlugin#9]
### What is happening?

I tried using commands to tp me to another player
/connectorplugin teleporttoplayer RoYing BoHer
and /connectorpluginvelocity teleporttoplayer RoYing BoHer

But they didn't teleport me to the player's side on another server
log ：Could not find server absurdworld-login on this proxy to send player RoYing to

### What did you expect to happen?

Transfer to another server and reach the player's side

### Version

1.5.2-SNAPSHOT (build 87)

### Config

```YAML
[VC config]
server-id: "absurdworld"
messenger-type: redis
——————————————————————
[BBBB server config]
messenger-type: redis
group: global
plugin-groups:
  pluginname: specialgroup
server-name: absurdworld-login
——————————————————————
[AAAA server config，in this server user command]
messenger-type: redis
group: global
plugin-groups:
  pluginname: specialgroup
server-name: absurdworld
```

### Server/system Version

vc3.3.0，paper1.12.2 andpaper1.20.4

### Log

```shell
[paper log]
[19:33:15 INFO]: RoYing issued server command: /connectorplugin teleporttoplayer RoYing BoHer
————————————————————————————————————————————
[VC log]
[connectorplugin]: [DEBUG] Could not find server absurdworld-login on this proxy to send player RoYing to
```

### What other programs/plugins are you running?

ViaRewind-3.0.6
ViaBackwards-4.9.2
ViaVersion-4.9.3
authmereload5.6.0

### Additional context

I tried to match server name with server id、Server name is different from server id、Each server has a different server name
It's of no use
